apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: real-devops-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
    - host: real-devops.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: real-devops-svc
                port:
                  number: 80

